import XCTest
@testable import Slimsy

final class ModelTests: XCTestCase {
    func testMetricConversionsKeepCanonicalPounds() {
        for pounds in [120.0, 176.4, 220.0, 400.0] {
            let kilograms = UnitSystem.metric.displayWeight(pounds)
            XCTAssertEqual(UnitSystem.metric.pounds(kilograms), pounds, accuracy: 0.000001)
        }
        XCTAssertEqual(UnitSystem.imperial.height(182.8), "6′ 0″")
    }

    func testLocalDayDoesNotShiftAtMidnight() {
        let athens = TimeZone(identifier: "Europe/Athens")!
        let date = ISO8601DateFormatter().date(from: "2026-09-25T21:30:00Z")!
        XCTAssertEqual(DayKey.string(date, timeZone: athens), "2026-09-26")
        XCTAssertEqual(DayKey.date("2026-09-26", time: "00:30", timeZone: athens), date)
        XCTAssertNil(DayKey.date("2026-02-30"))
        XCTAssertNil(DayKey.date("2026-09-26", time: "25:00"))
        XCTAssertNil(DayKey.date("not-a-date"))
    }

    func testDecimalInputRejectsPartialAndNonfiniteNumbers() {
        XCTAssertEqual("73,5".decimalValue, 73.5)
        XCTAssertEqual(" 176.4 ".decimalValue, 176.4)
        for invalid in ["12kg", "NaN", "Infinity", "1.2.3", "1,2,3", "", "1e999"] { XCTAssertNil(invalid.decimalValue, invalid) }
    }

    func testPKMatchesOriginalTypeScriptGoldenResults() {
        let now = DayKey.date("2026-09-23", time: "09:00")!
        let logs = [
            MedicationLog(date: "2026-09-20", time: "09:00", dose: "1 mg", deliveryType: .injection),
            MedicationLog(date: "2026-09-13", time: "09:00", dose: "1 mg", deliveryType: .injection)
        ]
        var profile = UserProfile()
        profile.medication = .wegovy
        profile.deliveryType = .injection
        profile.frequency = .weekly
        // Generated by running the existing utils/pharmacokinetics.ts at the
        // same local date/time; guards against accidental changes during the port.
        let semaglutide = Pharmacokinetics.compute(logs: logs, profile: profile, now: now)
        XCTAssertEqual(semaglutide.currentLevel, 99)
        XCTAssertEqual(semaglutide.curve[25].level, 0.9783171902019057, accuracy: 0.00000001)
        XCTAssertEqual(semaglutide.curve[100].level, 0.722411408092841, accuracy: 0.00000001)
        profile.medication = .mounjaro
        let tirzepatide = Pharmacokinetics.compute(logs: logs, profile: profile, now: now)
        XCTAssertEqual(tirzepatide.currentLevel, 92)
        XCTAssertEqual(tirzepatide.curve[50].level, 0.8648620094758653, accuracy: 0.00000001)
        profile.medication = .semaglutide
        profile.deliveryType = .pill
        profile.frequency = .daily
        let oral = Pharmacokinetics.compute(logs: logs, profile: profile, now: now)
        XCTAssertEqual(oral.currentLevel, 75)
        XCTAssertEqual(oral.curve[100].level, 0.9097680549048965, accuracy: 0.00000001)
    }

    func testPKHonorsCustomIntervalsAndExcludesFutureDoses() {
        let now = DayKey.date("2026-09-23", time: "09:00")!
        var p = UserProfile()
        p.frequency = .custom
        p.customFrequencyDays = 10
        let past = MedicationLog(date: "2026-09-20", time: "09:00", dose: "1 mg", deliveryType: .injection)
        let future = MedicationLog(date: "2026-10-10", time: "09:00", dose: "1 mg", deliveryType: .injection)
        let result = Pharmacokinetics.compute(logs: [past, future], profile: p, now: now)
        XCTAssertEqual(result.cycleHours, 240)
        XCTAssertEqual(result.daysUntilDose, 7, accuracy: 0.00001)
        XCTAssertEqual(result.currentLevel, Pharmacokinetics.compute(logs: [past], profile: p, now: now).currentLevel)
        XCTAssertTrue(Pharmacokinetics.compute(logs: [], profile: p, now: now).curve.isEmpty)
    }

    func testCountdownHandlesOverdueAndMinutePrecision() {
        let now = Date(timeIntervalSince1970: 1_000_000)
        let next = now.addingTimeInterval((2 * 1440 + 3 * 60 + 17) * 60)
        let countdown = DoseCountdown(nextDose: next, now: now)
        XCTAssertEqual(countdown.days, 2)
        XCTAssertEqual(countdown.hours, 3)
        XCTAssertEqual(countdown.minutes, 17)
        XCTAssertFalse(countdown.overdue)
        let overdue = DoseCountdown(nextDose: now.addingTimeInterval(-3600), now: now)
        XCTAssertTrue(overdue.overdue)
        XCTAssertEqual(overdue.days + overdue.hours + overdue.minutes, 0)
    }

    func testLegacyZustandBackupDecodesWithoutOptionalPreferences() throws {
        let json = #"{"state":{"preferences":{"units":"metric"},"userProfile":{"medication":"Wegovy","deliveryType":"injection","frequency":"custom","customFrequencyDays":10},"weightLogs":[{"id":"weight-1","date":"2026-09-20","weight":180}],"foodLogs":[],"waterLogs":[],"medicationLogs":[],"sideEffectLogs":[],"dailyTargets":{"calories":1400,"protein":100,"fiber":25,"water":8}},"version":0}"#
        let backup = try ExportService.decodeBackup(Data(json.utf8))
        XCTAssertEqual(backup.state.preferences.units, .metric)
        XCTAssertTrue(backup.state.preferences.doseReminders)
        XCTAssertEqual(backup.state.weightLogs.first?.weight, 180)
        XCTAssertEqual(backup.state.userProfile.intervalDays, 10)
        XCTAssertThrowsError(try ExportService.decodeBackup(Data("{}".utf8)))
    }

    func testBackupRoundtripAndCorruptRecordsAreRejected() throws {
        let data = AppData.demo()
        let encoded = try JSONEncoder().encode(ExportService.Backup(state: data))
        XCTAssertEqual(try ExportService.decodeBackup(encoded).state, data)
        var invalid = data
        invalid.weightLogs[0].weight = -3
        XCTAssertThrowsError(try invalid.validate())
        invalid = data
        invalid.weightLogs.append(invalid.weightLogs[0])
        XCTAssertThrowsError(try invalid.validate())
        invalid = data
        invalid.dailyTargets.water = 0
        XCTAssertThrowsError(try invalid.validate())
        invalid = data
        invalid.foodLogs[0].calories = 1e30
        XCTAssertThrowsError(try invalid.validate(), "Oversized values must not reach integer UI labels")
    }

    func testCSVContainsAllSectionsAndSafelyEscapesFreeText() {
        var data = AppData.demo()
        data.weightLogs[0].notes = "A note, with \"quotes\"\nand a new line"
        data.sideEffectLogs[0].notes = "=HYPERLINK(\"https://example.invalid\")"
        let csv = ExportService.csv(data)
        for section in ["USER PROFILE", "DAILY TARGETS", "WEIGHT LOGS", "FOOD LOGS", "MEDICATION LOGS", "SIDE EFFECT LOGS", "WATER LOGS"] { XCTAssertTrue(csv.contains("=== \(section) ===")) }
        XCTAssertTrue(csv.contains("\"A note, with \"\"quotes\"\"\nand a new line\""))
        XCTAssertTrue(csv.contains("'=HYPERLINK"))
        XCTAssertEqual(ExportService.csvCell("-2.5"), "-2.5")
    }

    func testNutritionParserHandlesMarkdownAndZeros() throws {
        let result = try NutritionEstimate.parse(Data(#"```json {"description":"A boiled egg","calories":78,"protein":6,"fiber":0,"carbs":0.6,"fat":5} ```"#.utf8))
        XCTAssertEqual(result.fiber, 0)
        XCTAssertEqual(result.calories, 78)
        XCTAssertThrowsError(try NutritionEstimate.parse(Data(#"{"description":"invalid","calories":-1,"protein":6,"fiber":0}"#.utf8)))
        XCTAssertThrowsError(try NutritionEstimate.parse(Data("No food found".utf8)))
        XCTAssertThrowsError(try NutritionEstimate.parse(Data(#"{"description":"invalid","calories":1e30,"protein":6,"fiber":0}"#.utf8)))
    }

    func testLegacyAsyncStorageMigrationSupportsInlineAndHashedFiles() throws {
        let directory = URL.temporaryDirectory.appending(path: UUID().uuidString)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        let original = AppData.demo()
        let bytes = try JSONEncoder().encode(ExportService.Backup(state: original))
        let manifest = directory.appending(path: "manifest.json")
        try JSONSerialization.data(withJSONObject: [LegacyMigration.key: String(decoding: bytes, as: UTF8.self)]).write(to: manifest)
        XCTAssertEqual(try LegacyMigration.load(storageDirectory: directory), original)
        try JSONSerialization.data(withJSONObject: [LegacyMigration.key: NSNull()]).write(to: manifest)
        let dataFile = directory.appending(path: LegacyMigration.keyFilename)
        try bytes.write(to: dataFile)
        XCTAssertEqual(try LegacyMigration.load(storageDirectory: directory), original)
        XCTAssertEqual(try Data(contentsOf: dataFile), bytes, "Migration must leave the original journal untouched")
    }
}

@MainActor
final class StoreTests: XCTestCase {
    func testDayRollsOverUnlessViewingHistory() {
        let yesterday = DayKey.date("2026-09-25", time: "23:59")!
        let today = DayKey.date("2026-09-26", time: "00:01")!
        let store = AppStore(fileURL: nil, schedulesReminders: false, now: yesterday)
        XCTAssertFalse(store.allowsNotifications)
        store.refreshCalendarDay(now: today)
        XCTAssertEqual(store.selectedDay, "2026-09-26")
        store.selectedDate = DayKey.date("2026-09-20")!
        store.refreshCalendarDay(now: DayKey.date("2026-09-27")!)
        XCTAssertEqual(store.selectedDay, "2026-09-20")
    }

    func testMostRecentSameDayWeighInIsCurrent() {
        let store = AppStore(fileURL: nil, initialData: .demo(), schedulesReminders: false)
        XCTAssertTrue(store.addWeight(WeightLog(date: DayKey.string(), weight: 175.2)))
        XCTAssertEqual(store.currentWeight, 175.2)
        XCTAssertEqual(store.profile.currentWeight, 175.2)
    }

    func testPersistenceAndChronologicalWeightAfterHistoricalEntryAndDeletion() throws {
        let directory = URL.temporaryDirectory.appending(path: UUID().uuidString)
        let file = directory.appending(path: "data.json")
        defer { try? FileManager.default.removeItem(at: directory) }
        let store = AppStore(fileURL: file, schedulesReminders: false)
        XCTAssertTrue(store.addWeight(WeightLog(id: "latest", date: "2026-09-25", weight: 175)))
        XCTAssertTrue(store.addWeight(WeightLog(id: "older", date: "2026-09-20", weight: 180)))
        XCTAssertEqual(store.currentWeight, 175)
        XCTAssertEqual(store.profile.currentWeight, 175)
        let restored = AppStore(fileURL: file, schedulesReminders: false)
        XCTAssertEqual(restored.data.weightLogs.count, 2)
        XCTAssertEqual(restored.currentWeight, 175)
        XCTAssertTrue(restored.deleteWeight("latest"))
        XCTAssertEqual(restored.currentWeight, 180)
    }

    func testFailedWriteDoesNotChangeMemoryAndCorruptFileIsNotOverwritten() throws {
        let dir = URL.temporaryDirectory.appending(path: UUID().uuidString)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }
        let file = dir.appending(path: "data.json")
        let corrupt = Data("not-json".utf8)
        try corrupt.write(to: file)
        let store = AppStore(fileURL: file, schedulesReminders: false)
        XCTAssertTrue(store.storageIsReadOnly)
        XCTAssertFalse(store.addWeight(WeightLog(date: "2026-09-25", weight: 175)))
        XCTAssertEqual(try Data(contentsOf: file), corrupt)
        XCTAssertTrue(store.data.weightLogs.isEmpty)

        let blockedParent = dir.appending(path: "a-file")
        try Data().write(to: blockedParent)
        let cannotWrite = AppStore(fileURL: blockedParent.appending(path: "data.json"), schedulesReminders: false)
        XCTAssertFalse(cannotWrite.addWeight(WeightLog(date: "2026-09-25", weight: 175)))
        XCTAssertTrue(cannotWrite.data.weightLogs.isEmpty)
    }

    func testDailyTotalsEditingDeletionAndWaterBounds() {
        let store = AppStore(fileURL: nil, schedulesReminders: false)
        let day = "2026-09-25"
        var food = FoodLog(date: day, mealType: .lunch, calories: 350, protein: 25, fiber: 5)
        XCTAssertTrue(store.saveFood(food))
        XCTAssertEqual(store.nutrition(on: day).calories, 350)
        food.calories = 450
        XCTAssertTrue(store.saveFood(food))
        XCTAssertEqual(store.data.foodLogs.count, 1)
        XCTAssertEqual(store.nutrition(on: day).calories, 450)
        XCTAssertEqual(store.nutrition(on: "2026-09-24").calories, 0)
        store.setWater(25, on: day)
        XCTAssertEqual(store.water(on: day), 20)
        store.setWater(-2, on: day)
        XCTAssertEqual(store.water(on: day), 0)
        store.deleteFood(food.id)
        XCTAssertEqual(store.nutrition(on: day).calories, 0)
    }

    func testDoseAndSymptomsAreSavedAtomicallyAndSiteRotates() {
        let store = AppStore(fileURL: nil, schedulesReminders: false)
        let log = MedicationLog(date: "2026-09-20", time: "09:00", dose: "1 mg", deliveryType: .injection, injectionSite: .abdomenLeft)
        let invalid = SideEffectLog(date: log.date, effectType: .nausea, severity: 7)
        XCTAssertFalse(store.addDose(log, symptoms: [invalid]))
        XCTAssertTrue(store.data.medicationLogs.isEmpty)
        XCTAssertTrue(store.addDose(log, symptoms: [SideEffectLog(date: log.date, effectType: .nausea, severity: 2)]))
        XCTAssertEqual(store.data.medicationLogs.count, 1)
        XCTAssertEqual(store.data.sideEffectLogs.count, 1)
        XCTAssertEqual(store.suggestedSite, .abdomenRight)
    }

    func testUnitSwitchDoesNotModifyStoredWeightsAndEqualGoalStaysFinite() {
        let store = AppStore(fileURL: nil, initialData: .demo(), schedulesReminders: false)
        let weights = store.data.weightLogs
        store.setUnits(.metric)
        XCTAssertEqual(store.data.weightLogs, weights)
        XCTAssertEqual(store.profile.weeklyGoalUnit, "kg")
        XCTAssertEqual(store.profile.weeklyGoal, 0.5)
        store.update { $0.userProfile.goalWeight = $0.userProfile.startWeight }
        XCTAssertEqual(store.goalProgress, 0)
        XCTAssertTrue(store.goalProgress.isFinite)
    }
}
